version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.4:9092 # 192.168.1.4 是虚拟机的iP
      KAFKA_CREATE_TOPICS: "test1:1:1" # 自动创建一个 名称为 test1 的 topic 分区是1 副本是1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 700800
    volumes:
      - /home/jyp/volume/kfksingle/kafka/logs:/kafka # kafak 数据挂载到主机地址
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:
      - kafka
      - zookeeper
    environment:
      KM_VERSION: 2.0.0.2
      ZK_HOSTS: "zookeeper"
      APPLICATION_SECRET: "letmein"